### PR TITLE
Multiple weapon fixes

### PR DESCRIPTION
**Pull request by NachosChipeados**
- Fixes barrage core's ``printname``, ``readymessage`` and ``readyhint`` not being localized.
- Fixes barrage core's ``shortprintname`` and descriptions using the wrong strings.
- Fixes cluster payload not having a ``sound_weapon_ready`` sound.

Before:
https://github.com/user-attachments/assets/8af85733-a07a-49b8-8195-9557d09b9f8b

After:
https://github.com/user-attachments/assets/d51eec56-4d3b-4390-b539-b24026cd0874

- Can no longer use cluster payload while having max ammo, as it ocasionally caused issues.

Before:
https://github.com/user-attachments/assets/c5d4607b-f150-4b8d-a8b3-f8dff2dc8b33

After:
https://github.com/user-attachments/assets/eeeb8aba-b26c-4a01-b68f-dae5c1392c75

### CODE REVIEW

**Comment by Dinorush** [comment]
What issues did using Cluster Payload at max ammo cause?

**Comment by NachosChipeados** [comment]
It ocasionally would set your ammo to 0 as intended but wouldn't reload until you did it manually, or made any other actions (sprinting, using grenade volley, melee). Sorry if i didn't make it clear enough in its before video, thats my bad.

**Comment by NachosChipeados** [comment]
https://github.com/user-attachments/assets/1df99b4a-48f0-4560-8d73-0d23477edec5

**Comment by NachosChipeados** [comment]
I've also considered adding a hudhint when trying to use Cluster Payload at max ammo, similar to Rearm or Tracking Rockets, so its more obvious why someone can't use it. Should i pr this as well or do you think its too much?
Screenshot 2024-09-08 114524

Edit: just saw the latest commit, guess this isn't neccesary anymore

**Comment by Dinorush** [comment]
I updated the cluster payload logic a bit. Animation is smoother now when canceling a reload (not always, but nice when it works) and I added the forced holster/deploy if the weapon wasn't reloading to fix the bug above. Would rather it be able to be used at full mag if possible. Could you pull it down and see if it works for you? I couldn't even replicate the bug pre-patch myself after like 20 tries.

**Comment by NachosChipeados** [comment]
Will do, give me a sec

**Comment by NachosChipeados** [comment]
Yeah, can confirm it doesn't happen anymore.

**Pull request merged**
